language: node_js
cache: yarn
node_js:
- '10'
jobs:
  include:
  - stage: build
    script: 
        - yarn build:server
        - yarn build:client

before_deploy:
  - cd ./server/dist
  - tar -zcf server.tar.gz *

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./server/dist/server.tar.gz
  skip_cleanup: true
  draft: true
  on:
    branch: travis-ci-deploy
