language: node_js
cache: yarn
node_js:
- '10'
jobs:
  include:
  - stage: build
    script: 
        - yarn build:server
        - yarn build:client
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: README.md
  skip_cleanup: true
  draft: true
  on:
    branch: travis-ci-deploy
